# Imports and preprocessing

## Imports

In [1]:
import pandas as pd

In [2]:
from sklearn.preprocessing import OneHotEncoder

## Teams DB

In [3]:
data = pd.read_csv('data/england-premier-league-teams-2018-to-2019-stats.csv')

In [4]:
data.head(5)

,team_name,common_name,season,country,matches_played,matches_played_home,matches_played_away,suspended_matches,wins,wins_home,...,goals_conceded_min_61_to_70,goals_conceded_min_71_to_80,goals_conceded_min_81_to_90,draw_percentage_overall,draw_percentage_home,draw_percentage_away,loss_percentage_ovearll,loss_percentage_home,loss_percentage_away,over145_corners_percentage
0,Arsenal FC,Arsenal,2018/2019,England,38,19,19,0,21,14,...,12,1,8,18,16,21,26,11,42,5
1,Tottenham Hotspur FC,Tottenham Hotspur,2018/2019,England,38,19,19,0,23,12,...,4,8,10,5,11,0,34,26,42,11
2,Manchester City FC,Manchester City,2018/2019,England,38,19,19,0,32,18,...,4,2,3,5,0,11,11,5,16,5
3,Leicester City FC,Leicester City,2018/2019,England,38,19,19,0,15,8,...,7,1,9,18,16,21,42,42,42,5
4,Crystal Palace FC,Crystal Palace,2018/2019,England,38,19,19,0,14,5,...,8,8,11,18,26,11,45,47,42,11

In [5]:
start_data = data[['common_name','matches_played', 'wins', 'wins_home','wins_away','losses_home','losses_away', 'losses']]

In [6]:
start_data['home_percentage'] = (start_data['wins_home']/19).round(2)

/var/folders/0y/5bdrgh9x1vq3vcp3pz35y9jr0000gn/T/ipykernel_56211/3343339179.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  start_data['home_percentage'] = (start_data['wins_home']/19).round(2)

In [7]:
start_data['away_percentage'] = (start_data['wins_away']/19).round(2)

/var/folders/0y/5bdrgh9x1vq3vcp3pz35y9jr0000gn/T/ipykernel_56211/4018960548.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  start_data['away_percentage'] = (start_data['wins_away']/19).round(2)

In [8]:
start_data['points'] = (data['points_per_game']*38).round(0)

/var/folders/0y/5bdrgh9x1vq3vcp3pz35y9jr0000gn/T/ipykernel_56211/400297253.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  start_data['points'] = (data['points_per_game']*38).round(0)

In [9]:
start_data.sort_values('points', ascending = False)

,common_name,matches_played,wins,wins_home,wins_away,losses_home,losses_away,losses,home_percentage,away_percentage,points
2,Manchester City,38,32,18,14,1,3,4,0.95,0.74,98.0
10,Liverpool,38,30,17,13,0,1,1,0.89,0.68,97.0
11,Chelsea,38,21,12,9,1,7,8,0.63,0.47,72.0
1,Tottenham Hotspur,38,23,12,11,5,8,13,0.63,0.58,71.0
0,Arsenal,38,21,14,7,2,8,10,0.74,0.37,70.0
9,Manchester United,38,19,10,9,3,7,10,0.53,0.47,66.0
19,Wolverhampton Wanderers,38,16,10,6,5,8,13,0.53,0.32,57.0
5,Everton,38,15,10,5,5,9,14,0.53,0.26,54.0
3,Leicester City,38,15,8,7,8,8,16,0.42,0.37,52.0
12,West Ham United,38,15,9,6,6,10,16,0.47,0.32,52.0
13,Watford,38,14,8,6,8,8,16,0.42,0.32,50.0
4,Crystal Palace,38,14,5,9,9,8,17,0.26,0.47,49.0
8,AFC Bournemouth,38,13,8,5,6,13,19,0.42,0.26,45.0
14,Newcastle United,38,12,8,4,10,7,17,0.42,0.21,45.0
6,Burnley,38,11,7,4,10,10,20,0.37,0.21,40.0
7,Southampton,38,9,5,4,6,11,17,0.26,0.21,39.0
17,Brighton & Hove Albion,38,9,6,3,8,12,20,0.32,0.16,36.0
15,Cardiff City,38,10,6,4,11,13,24,0.32,0.21,34.0
16,Fulham,38,7,6,1,10,16,26,0.32,0.05,26.0
18,Huddersfield Town,38,3,2,1,14,14,28,0.11,0.05,16.0

## Matches DB

In [10]:
match_data = pd.read_csv('data/england-premier-league-matches-2018-to-2019-stats.csv')

In [11]:
match_data.head(5)

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,Pre-Match PPG (Home),Pre-Match PPG (Away),...,odds_ft_home_team_win,odds_ft_draw,odds_ft_away_team_win,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_btts_yes,odds_btts_no,stadium_name
0,1533927600,Aug 10 2018 - 7:00pm,complete,74439,Manchester United,Leicester City,Andre Marriner,1,0.0,0.0,...,1.37,4.98,9.81,1.33,2.00,3.60,7.50,2.05,1.69,Old Trafford (Manchester)
1,1533987000,Aug 11 2018 - 11:30am,complete,51749,Newcastle United,Tottenham Hotspur,Martin Atkinson,1,0.0,0.0,...,4.51,3.77,1.84,1.31,1.95,3.50,5.75,1.83,1.87,St. James' Park (Newcastle upon Tyne)
2,1533996000,Aug 11 2018 - 2:00pm,complete,10353,AFC Bournemouth,Cardiff City,Kevin Friend,1,0.0,0.0,...,2.03,3.51,3.96,1.31,1.95,3.45,6.70,1.83,1.83,Vitality Stadium (Bournemouth- Dorset)
3,1533996000,Aug 11 2018 - 2:00pm,complete,24821,Fulham,Crystal Palace,Mike Dean,1,0.0,0.0,...,2.31,3.44,3.26,1.28,1.87,3.20,7.00,1.71,2.00,Craven Cottage (London)
4,1533996000,Aug 11 2018 - 2:00pm,complete,24121,Huddersfield Town,Chelsea,Chris Kavanagh,1,0.0,0.0,...,7.47,4.27,1.51,1.29,1.91,3.30,6.95,2.00,1.71,John Smith's Stadium (Huddersfield- West Yorks...

In [12]:
match_data_pre = match_data.drop('timestamp', axis = 1)

In [13]:
match_data_pre = match_data.drop('home_ppg', axis = 1)
match_data_pre = match_data.drop('away_ppg', axis = 1)

In [14]:
match_data_pre = match_data_pre[['home_team_name', 'away_team_name', 'home_team_goal_count', 'away_team_goal_count']]

In [15]:
match_data_pre

,home_team_name,away_team_name,home_team_goal_count,away_team_goal_count
0,Manchester United,Leicester City,2,1
1,Newcastle United,Tottenham Hotspur,1,2
2,AFC Bournemouth,Cardiff City,2,0
3,Fulham,Crystal Palace,0,2
4,Huddersfield Town,Chelsea,0,3
...,...,...,...,...
375,Liverpool,Wolverhampton Wanderers,2,0
376,Manchester United,Cardiff City,0,2
377,Southampton,Huddersfield Town,1,1
378,Tottenham Hotspur,Everton,2,2
379,Watford,West Ham United,1,4

In [16]:
match_data_pre['away_team_away_percentage'] = 0
match_data_pre['home_team_home_percentage'] = 0

In [17]:
for i in range(0, len(match_data_pre)):
    for j in range(0, len(start_data)):
        if match_data_pre['home_team_name'][i] == start_data['common_name'][j]:
            match_data_pre['home_team_home_percentage'][i] = start_data['home_percentage'][j]
            
        if match_data_pre['away_team_name'][i] == start_data['common_name'][j]:
            match_data_pre['away_team_away_percentage'][i] = start_data['away_percentage'][j]

/var/folders/0y/5bdrgh9x1vq3vcp3pz35y9jr0000gn/T/ipykernel_56211/1453583459.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_data_pre['away_team_away_percentage'][i] = start_data['away_percentage'][j]
/var/folders/0y/5bdrgh9x1vq3vcp3pz35y9jr0000gn/T/ipykernel_56211/1453583459.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_data_pre['home_team_home_percentage'][i] = start_data['home_percentage'][j]

In [18]:
ohe = OneHotEncoder(sparse_output = False)
ohe.fit(match_data_pre[['home_team_name']])

OneHotEncoder(sparse_output=False)

In [19]:
match_data_pre[ohe.get_feature_names_out()] = ohe.transform(match_data_pre[['home_team_name']])

match_data_pre.drop(columns = ["home_team_name"], inplace = True)

In [20]:
ohe = OneHotEncoder(sparse_output = False)
ohe.fit(match_data_pre[['away_team_name']])

OneHotEncoder(sparse_output=False)

In [21]:
match_data_pre[ohe.get_feature_names_out()] = ohe.transform(match_data_pre[['away_team_name']])

match_data_pre.drop(columns = ["away_team_name"], inplace = True)

In [22]:
match_data_pre['home_win'] = 0
match_data_pre['away_win'] = 0

In [23]:
for i in range(0,len(match_data_pre)):
    if match_data_pre['home_team_goal_count'][i] > match_data_pre['away_team_goal_count'][i]:
        match_data_pre['home_win'][i] = 1
        match_data_pre['away_win'][i] = 0
    elif match_data_pre['home_team_goal_count'][i] < match_data_pre['away_team_goal_count'][i]:
        match_data_pre['away_win'][i] = 1
        match_data_pre['home_win'][i] = 0

for i in range(0,len(match_data_pre)):
    if match_data_pre['home_win'][i] == 0 and match_data_pre['away_win'][i] == 0:
        match_data_pre['home_win'][i] = 0.5
        match_data_pre['away_win'][i] = 0.5

/var/folders/0y/5bdrgh9x1vq3vcp3pz35y9jr0000gn/T/ipykernel_56211/969261203.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_data_pre['home_win'][i] = 1
/var/folders/0y/5bdrgh9x1vq3vcp3pz35y9jr0000gn/T/ipykernel_56211/969261203.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_data_pre['away_win'][i] = 0
/var/folders/0y/5bdrgh9x1vq3vcp3pz35y9jr0000gn/T/ipykernel_56211/969261203.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_data_pre['away_win'][i] = 1
/var/folders/0y/5bdrgh9x1vq3vcp3pz35y9jr0000gn/T/ipykernel_56211/969261203.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_data_pre['home_win'][i] = 0
/var/folders/0y/5bdrgh9x1vq3vcp3pz35y9jr0000gn/T/ipykernel_56211/969261203.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_data_pre['home_win'][i] = 0.5
/var/folders/0y/5bdrgh9x1vq3vcp3pz35y9jr0000gn/T/ipykernel_56211/969261203.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_data_pre['away_win'][i] = 0.5

In [24]:
match_data_pre['gameweek'] = match_data['Game Week']

In [25]:
match_data_pre[:369]

,home_team_goal_count,away_team_goal_count,away_team_away_percentage,home_team_home_percentage,home_team_name_AFC Bournemouth,home_team_name_Arsenal,home_team_name_Brighton & Hove Albion,home_team_name_Burnley,home_team_name_Cardiff City,home_team_name_Chelsea,...,away_team_name_Manchester United,away_team_name_Newcastle United,away_team_name_Southampton,away_team_name_Tottenham Hotspur,away_team_name_Watford,away_team_name_West Ham United,away_team_name_Wolverhampton Wanderers,home_win,away_win,gameweek
0,2,1,0.37,0.53,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1
1,1,2,0.58,0.42,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1
2,2,0,0.21,0.42,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1
3,0,2,0.47,0.32,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
4,0,3,0.47,0.11,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,2,3,0.47,0.32,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,37
365,2,3,0.68,0.42,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,37
366,3,0,0.32,0.63,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,37
367,1,1,0.47,0.11,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.5,37
368,1,1,0.16,0.74,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.5,37

## Preprocessing

In [26]:
X_train = match_data_pre[:359]

In [27]:
X_train = X_train.drop('home_win', axis = 1)

In [28]:
X_train = X_train.drop('away_win', axis = 1)

In [29]:
X_train = X_train.drop('home_team_goal_count', axis = 1)
X_train = X_train.drop('away_team_goal_count', axis = 1)

In [30]:
X_train = X_train.drop('gameweek', axis = 1)

In [31]:
X_train

,away_team_away_percentage,home_team_home_percentage,home_team_name_AFC Bournemouth,home_team_name_Arsenal,home_team_name_Brighton & Hove Albion,home_team_name_Burnley,home_team_name_Cardiff City,home_team_name_Chelsea,home_team_name_Crystal Palace,home_team_name_Everton,...,away_team_name_Leicester City,away_team_name_Liverpool,away_team_name_Manchester City,away_team_name_Manchester United,away_team_name_Newcastle United,away_team_name_Southampton,away_team_name_Tottenham Hotspur,away_team_name_Watford,away_team_name_West Ham United,away_team_name_Wolverhampton Wanderers
0,0.37,0.53,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.58,0.42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.21,0.42,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.47,0.32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.47,0.11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,0.26,0.26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
355,0.32,0.42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
356,0.21,0.32,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
357,0.37,0.42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
358,0.74,0.37,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
y_train = match_data_pre[:359]

In [33]:
y_train = y_train[['home_win', 'away_win']]

In [34]:
X_test = match_data_pre[360:370]

In [35]:
X_test = X_test.drop('home_team_goal_count', axis = 1)
X_test = X_test.drop('away_team_goal_count', axis = 1)
X_test = X_test.drop('away_win', axis = 1)
X_test = X_test.drop('home_win', axis = 1)
X_test = X_test.drop('gameweek', axis = 1)

In [36]:
X_test

,away_team_away_percentage,home_team_home_percentage,home_team_name_AFC Bournemouth,home_team_name_Arsenal,home_team_name_Brighton & Hove Albion,home_team_name_Burnley,home_team_name_Cardiff City,home_team_name_Chelsea,home_team_name_Crystal Palace,home_team_name_Everton,...,away_team_name_Leicester City,away_team_name_Liverpool,away_team_name_Manchester City,away_team_name_Manchester United,away_team_name_Newcastle United,away_team_name_Southampton,away_team_name_Tottenham Hotspur,away_team_name_Watford,away_team_name_West Ham United,away_team_name_Wolverhampton Wanderers
360,0.21,0.53,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
361,0.58,0.42,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
362,0.21,0.47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
363,0.05,0.53,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
364,0.47,0.32,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
365,0.68,0.42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
366,0.32,0.63,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
367,0.47,0.11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
368,0.16,0.74,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
369,0.37,0.95,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
y_test = match_data_pre[360:370]

In [38]:
y_test = y_train[['home_win', 'away_win']]

# Beginning with the Models

## Imports

In [39]:
from tensorflow.keras import models, layers

In [40]:
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam

## Early Tests

In [41]:
mean_absolute_error_test_baseline = abs((y_train - y_train.mean())).mean()
mean_absolute_error_test_baseline

home_win    0.412093
away_win    0.412093
dtype: float64

In [42]:
def initialize_model():
    model = models.Sequential()
    
    model.add(layers.Dense(10, activation = 'relu', input_dim = X_train.shape[-1]))
    model.add(layers.Dense(7, activation = 'relu'))
    model.add(layers.Dense(2, activation = 'softmax'))
    
    return model

In [43]:
model = initialize_model()

In [44]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 10)                430

 dense_1 (Dense)             (None, 7)                 77

 dense_2 (Dense)             (None, 2)                 16

=================================================================
Total params: 523
Trainable params: 523
Non-trainable params: 0
_________________________________________________________________

In [45]:
def compile_model(model, optimizer_name):
    model_compiled = model.compile(optimizer = optimizer_name,
                  loss = 'BinaryCrossentropy',
                  metrics='accuracy'
    )
    return model_compiled

In [46]:
compile_model(model, 'Adam')

In [47]:
es = EarlyStopping(patience = 100, restore_best_weights=True)

history = model.fit(X_train, y_train, batch_size = 16, epochs = 500, validation_split = 0.2, callbacks = [es])

Epoch 1/500

2024-02-03 14:40:35.068229: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz

18/18 [==============================] - 0s 6ms/step - loss: 0.7125 - accuracy: 0.3554 - val_loss: 0.7040 - val_accuracy: 0.4167
Epoch 2/500
18/18 [==============================] - 0s 1ms/step - loss: 0.7029 - accuracy: 0.3763 - val_loss: 0.6971 - val_accuracy: 0.4861
Epoch 3/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6961 - accuracy: 0.4460 - val_loss: 0.6914 - val_accuracy: 0.5278
Epoch 4/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6903 - accuracy: 0.5331 - val_loss: 0.6874 - val_accuracy: 0.5556
Epoch 5/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6860 - accuracy: 0.5645 - val_loss: 0.6836 - val_accuracy: 0.5694
Epoch 6/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6810 - accuracy: 0.6272 - val_loss: 0.6811 - val_accuracy: 0.6111
Epoch 7/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6769 - accuracy: 0.6516 - val_loss: 0.6780 - val_accuracy: 0.6111
Epoch 8/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6708 - accuracy: 0.6794 - val_loss: 0.6750 - val_accuracy: 0.5972
Epoch 9/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6652 - accuracy: 0.6829 - val_loss: 0.6720 - val_accuracy: 0.5833
Epoch 10/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6591 - accuracy: 0.7038 - val_loss: 0.6688 - val_accuracy: 0.5694
Epoch 11/500
18/18 [==============================] - 0s 960us/step - loss: 0.6531 - accuracy: 0.6969 - val_loss: 0.6654 - val_accuracy: 0.5972
Epoch 12/500
18/18 [==============================] - 0s 985us/step - loss: 0.6466 - accuracy: 0.7282 - val_loss: 0.6613 - val_accuracy: 0.6250
Epoch 13/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6392 - accuracy: 0.7352 - val_loss: 0.6582 - val_accuracy: 0.6250
Epoch 14/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6326 - accuracy: 0.7526 - val_loss: 0.6533 - val_accuracy: 0.6389
Epoch 15/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6242 - accuracy: 0.7700 - val_loss: 0.6487 - val_accuracy: 0.6528
Epoch 16/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6154 - accuracy: 0.7700 - val_loss: 0.6446 - val_accuracy: 0.7222
Epoch 17/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6063 - accuracy: 0.7840 - val_loss: 0.6403 - val_accuracy: 0.7361
Epoch 18/500
18/18 [==============================] - 0s 1ms/step - loss: 0.5974 - accuracy: 0.7875 - val_loss: 0.6358 - val_accuracy: 0.7500
Epoch 19/500
18/18 [==============================] - 0s 1ms/step - loss: 0.5876 - accuracy: 0.7805 - val_loss: 0.6336 - val_accuracy: 0.7361
Epoch 20/500
18/18 [==============================] - 0s 1ms/step - loss: 0.5783 - accuracy: 0.8084 - val_loss: 0.6294 - val_accuracy: 0.7361
Epoch 21/500
18/18 [==============================] - 0s 1ms/step - loss: 0.5681 - accuracy: 0.8188 - val_loss: 0.6276 - val_accuracy: 0.7361
Epoch 22/500
18/18 [==============================] - 0s 1ms/step - loss: 0.5591 - accuracy: 0.8118 - val_loss: 0.6260 - val_accuracy: 0.7361
Epoch 23/500
18/18 [==============================] - 0s 1ms/step - loss: 0.5501 - accuracy: 0.8118 - val_loss: 0.6250 - val_accuracy: 0.7361
Epoch 24/500
18/18 [==============================] - 0s 1ms/step - loss: 0.5412 - accuracy: 0.8014 - val_loss: 0.6248 - val_accuracy: 0.7361
Epoch 25/500
18/18 [==============================] - 0s 1ms/step - loss: 0.5324 - accuracy: 0.8118 - val_loss: 0.6239 - val_accuracy: 0.7083
Epoch 26/500
18/18 [==============================] - 0s 938us/step - loss: 0.5248 - accuracy: 0.8049 - val_loss: 0.6257 - val_accuracy: 0.7083
Epoch 27/500
18/18 [==============================] - 0s 973us/step - loss: 0.5170 - accuracy: 0.8049 - val_loss: 0.6265 - val_accuracy: 0.7083
Epoch 28/500
18/18 [==============================] - 0s 996us/step - loss: 0.5094 - accuracy: 0.8084 - val_loss: 0.6275 - val_accuracy: 0.7083
Epoch 29/500
18/18 [==============================] - 0s 1ms/step - loss: 0.5033 - accuracy: 0.8049 - val_loss: 0.6302 - val_accuracy: 0.7083
Epoch 30/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4977 - accuracy: 0.8153 - val_loss: 0.6330 - val_accuracy: 0.7083
Epoch 31/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4916 - accuracy: 0.8118 - val_loss: 0.6364 - val_accuracy: 0.7222
Epoch 32/500
18/18 [==============================] - 0s 996us/step - loss: 0.4869 - accuracy: 0.8084 - val_loss: 0.6415 - val_accuracy: 0.7083
Epoch 33/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4818 - accuracy: 0.8049 - val_loss: 0.6432 - val_accuracy: 0.7083
Epoch 34/500
18/18 [==============================] - 0s 934us/step - loss: 0.4779 - accuracy: 0.8049 - val_loss: 0.6483 - val_accuracy: 0.6806
Epoch 35/500
18/18 [==============================] - 0s 973us/step - loss: 0.4733 - accuracy: 0.7944 - val_loss: 0.6499 - val_accuracy: 0.6667
Epoch 36/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4692 - accuracy: 0.8049 - val_loss: 0.6524 - val_accuracy: 0.6667
Epoch 37/500
18/18 [==============================] - 0s 977us/step - loss: 0.4656 - accuracy: 0.8014 - val_loss: 0.6567 - val_accuracy: 0.6667
Epoch 38/500
18/18 [==============================] - 0s 957us/step - loss: 0.4615 - accuracy: 0.8084 - val_loss: 0.6572 - val_accuracy: 0.6667
Epoch 39/500
18/18 [==============================] - 0s 963us/step - loss: 0.4577 - accuracy: 0.8049 - val_loss: 0.6600 - val_accuracy: 0.6667
Epoch 40/500
18/18 [==============================] - 0s 961us/step - loss: 0.4552 - accuracy: 0.8049 - val_loss: 0.6651 - val_accuracy: 0.6667
Epoch 41/500
18/18 [==============================] - 0s 961us/step - loss: 0.4504 - accuracy: 0.8153 - val_loss: 0.6635 - val_accuracy: 0.6806
Epoch 42/500
18/18 [==============================] - 0s 981us/step - loss: 0.4480 - accuracy: 0.8153 - val_loss: 0.6669 - val_accuracy: 0.6667
Epoch 43/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4448 - accuracy: 0.8258 - val_loss: 0.6702 - val_accuracy: 0.6667
Epoch 44/500
18/18 [==============================] - 0s 2ms/step - loss: 0.4426 - accuracy: 0.8223 - val_loss: 0.6696 - val_accuracy: 0.6667
Epoch 45/500
18/18 [==============================] - 0s 989us/step - loss: 0.4390 - accuracy: 0.8153 - val_loss: 0.6733 - val_accuracy: 0.6667
Epoch 46/500
18/18 [==============================] - 0s 964us/step - loss: 0.4360 - accuracy: 0.8258 - val_loss: 0.6711 - val_accuracy: 0.6667
Epoch 47/500
18/18 [==============================] - 0s 945us/step - loss: 0.4338 - accuracy: 0.8293 - val_loss: 0.6752 - val_accuracy: 0.6528
Epoch 48/500
18/18 [==============================] - 0s 943us/step - loss: 0.4314 - accuracy: 0.8258 - val_loss: 0.6748 - val_accuracy: 0.6528
Epoch 49/500
18/18 [==============================] - 0s 975us/step - loss: 0.4278 - accuracy: 0.8328 - val_loss: 0.6770 - val_accuracy: 0.6528
Epoch 50/500
18/18 [==============================] - 0s 946us/step - loss: 0.4257 - accuracy: 0.8293 - val_loss: 0.6792 - val_accuracy: 0.6528
Epoch 51/500
18/18 [==============================] - 0s 955us/step - loss: 0.4224 - accuracy: 0.8258 - val_loss: 0.6811 - val_accuracy: 0.6528
Epoch 52/500
18/18 [==============================] - 0s 970us/step - loss: 0.4194 - accuracy: 0.8328 - val_loss: 0.6836 - val_accuracy: 0.6528
Epoch 53/500
18/18 [==============================] - 0s 971us/step - loss: 0.4173 - accuracy: 0.8293 - val_loss: 0.6837 - val_accuracy: 0.6528
Epoch 54/500
18/18 [==============================] - 0s 968us/step - loss: 0.4149 - accuracy: 0.8293 - val_loss: 0.6868 - val_accuracy: 0.6528
Epoch 55/500
18/18 [==============================] - 0s 966us/step - loss: 0.4119 - accuracy: 0.8223 - val_loss: 0.6889 - val_accuracy: 0.6528
Epoch 56/500
18/18 [==============================] - 0s 976us/step - loss: 0.4094 - accuracy: 0.8223 - val_loss: 0.6910 - val_accuracy: 0.6528
Epoch 57/500
18/18 [==============================] - 0s 954us/step - loss: 0.4065 - accuracy: 0.8188 - val_loss: 0.6940 - val_accuracy: 0.6528
Epoch 58/500

18/18 [==============================] - 0s 955us/step - loss: 0.4043 - accuracy: 0.8258 - val_loss: 0.6922 - val_accuracy: 0.6528
Epoch 59/500
18/18 [==============================] - 0s 963us/step - loss: 0.4017 - accuracy: 0.8293 - val_loss: 0.6948 - val_accuracy: 0.6528
Epoch 60/500
18/18 [==============================] - 0s 960us/step - loss: 0.3996 - accuracy: 0.8188 - val_loss: 0.6988 - val_accuracy: 0.6528
Epoch 61/500
18/18 [==============================] - 0s 944us/step - loss: 0.3971 - accuracy: 0.8293 - val_loss: 0.6998 - val_accuracy: 0.6528
Epoch 62/500
18/18 [==============================] - 0s 975us/step - loss: 0.3944 - accuracy: 0.8362 - val_loss: 0.6999 - val_accuracy: 0.6528
Epoch 63/500
18/18 [==============================] - 0s 955us/step - loss: 0.3920 - accuracy: 0.8328 - val_loss: 0.7009 - val_accuracy: 0.6528
Epoch 64/500
18/18 [==============================] - 0s 966us/step - loss: 0.3898 - accuracy: 0.8258 - val_loss: 0.7027 - val_accuracy: 0.6667
Epoch 65/500
18/18 [==============================] - 0s 923us/step - loss: 0.3875 - accuracy: 0.8328 - val_loss: 0.7055 - val_accuracy: 0.6667
Epoch 66/500
18/18 [==============================] - 0s 939us/step - loss: 0.3850 - accuracy: 0.8293 - val_loss: 0.7037 - val_accuracy: 0.6667
Epoch 67/500
18/18 [==============================] - 0s 977us/step - loss: 0.3834 - accuracy: 0.8397 - val_loss: 0.7066 - val_accuracy: 0.6667
Epoch 68/500
18/18 [==============================] - 0s 938us/step - loss: 0.3805 - accuracy: 0.8328 - val_loss: 0.7078 - val_accuracy: 0.6667
Epoch 69/500
18/18 [==============================] - 0s 966us/step - loss: 0.3785 - accuracy: 0.8258 - val_loss: 0.7082 - val_accuracy: 0.6667
Epoch 70/500
18/18 [==============================] - 0s 960us/step - loss: 0.3760 - accuracy: 0.8362 - val_loss: 0.7089 - val_accuracy: 0.6667
Epoch 71/500
18/18 [==============================] - 0s 944us/step - loss: 0.3735 - accuracy: 0.8397 - val_loss: 0.7093 - val_accuracy: 0.6806
Epoch 72/500
18/18 [==============================] - 0s 963us/step - loss: 0.3712 - accuracy: 0.8293 - val_loss: 0.7119 - val_accuracy: 0.6806
Epoch 73/500
18/18 [==============================] - 0s 935us/step - loss: 0.3689 - accuracy: 0.8432 - val_loss: 0.7101 - val_accuracy: 0.6944
Epoch 74/500
18/18 [==============================] - 0s 929us/step - loss: 0.3659 - accuracy: 0.8502 - val_loss: 0.7134 - val_accuracy: 0.6806
Epoch 75/500
18/18 [==============================] - 0s 942us/step - loss: 0.3648 - accuracy: 0.8432 - val_loss: 0.7144 - val_accuracy: 0.6667
Epoch 76/500
18/18 [==============================] - 0s 957us/step - loss: 0.3635 - accuracy: 0.8502 - val_loss: 0.7098 - val_accuracy: 0.6944
Epoch 77/500
18/18 [==============================] - 0s 951us/step - loss: 0.3597 - accuracy: 0.8502 - val_loss: 0.7160 - val_accuracy: 0.6806
Epoch 78/500
18/18 [==============================] - 0s 938us/step - loss: 0.3571 - accuracy: 0.8432 - val_loss: 0.7134 - val_accuracy: 0.6944
Epoch 79/500
18/18 [==============================] - 0s 970us/step - loss: 0.3546 - accuracy: 0.8537 - val_loss: 0.7156 - val_accuracy: 0.6944
Epoch 80/500
18/18 [==============================] - 0s 918us/step - loss: 0.3527 - accuracy: 0.8676 - val_loss: 0.7171 - val_accuracy: 0.6944
Epoch 81/500
18/18 [==============================] - 0s 953us/step - loss: 0.3500 - accuracy: 0.8641 - val_loss: 0.7204 - val_accuracy: 0.6944
Epoch 82/500
18/18 [==============================] - 0s 960us/step - loss: 0.3477 - accuracy: 0.8606 - val_loss: 0.7210 - val_accuracy: 0.6944
Epoch 83/500
18/18 [==============================] - 0s 962us/step - loss: 0.3456 - accuracy: 0.8606 - val_loss: 0.7205 - val_accuracy: 0.6806
Epoch 84/500
18/18 [==============================] - 0s 953us/step - loss: 0.3436 - accuracy: 0.8606 - val_loss: 0.7194 - val_accuracy: 0.6944
Epoch 85/500
18/18 [==============================] - 0s 977us/step - loss: 0.3409 - accuracy: 0.8641 - val_loss: 0.7207 - val_accuracy: 0.6944
Epoch 86/500
18/18 [==============================] - 0s 958us/step - loss: 0.3392 - accuracy: 0.8571 - val_loss: 0.7205 - val_accuracy: 0.6944
Epoch 87/500
18/18 [==============================] - 0s 962us/step - loss: 0.3371 - accuracy: 0.8606 - val_loss: 0.7228 - val_accuracy: 0.6944
Epoch 88/500
18/18 [==============================] - 0s 954us/step - loss: 0.3348 - accuracy: 0.8571 - val_loss: 0.7231 - val_accuracy: 0.6944
Epoch 89/500
18/18 [==============================] - 0s 949us/step - loss: 0.3334 - accuracy: 0.8537 - val_loss: 0.7267 - val_accuracy: 0.6944
Epoch 90/500
18/18 [==============================] - 0s 953us/step - loss: 0.3307 - accuracy: 0.8641 - val_loss: 0.7247 - val_accuracy: 0.7083
Epoch 91/500
18/18 [==============================] - 0s 951us/step - loss: 0.3287 - accuracy: 0.8571 - val_loss: 0.7279 - val_accuracy: 0.7083
Epoch 92/500
18/18 [==============================] - 0s 935us/step - loss: 0.3259 - accuracy: 0.8606 - val_loss: 0.7276 - val_accuracy: 0.7083
Epoch 93/500
18/18 [==============================] - 0s 964us/step - loss: 0.3249 - accuracy: 0.8676 - val_loss: 0.7289 - val_accuracy: 0.7083
Epoch 94/500
18/18 [==============================] - 0s 946us/step - loss: 0.3227 - accuracy: 0.8641 - val_loss: 0.7284 - val_accuracy: 0.7083
Epoch 95/500
18/18 [==============================] - 0s 944us/step - loss: 0.3213 - accuracy: 0.8780 - val_loss: 0.7317 - val_accuracy: 0.6944
Epoch 96/500
18/18 [==============================] - 0s 958us/step - loss: 0.3184 - accuracy: 0.8746 - val_loss: 0.7320 - val_accuracy: 0.6944
Epoch 97/500
18/18 [==============================] - 0s 951us/step - loss: 0.3167 - accuracy: 0.8746 - val_loss: 0.7313 - val_accuracy: 0.6944
Epoch 98/500
18/18 [==============================] - 0s 965us/step - loss: 0.3150 - accuracy: 0.8711 - val_loss: 0.7325 - val_accuracy: 0.6806
Epoch 99/500
18/18 [==============================] - 0s 982us/step - loss: 0.3137 - accuracy: 0.8746 - val_loss: 0.7349 - val_accuracy: 0.6806
Epoch 100/500
18/18 [==============================] - 0s 938us/step - loss: 0.3118 - accuracy: 0.8711 - val_loss: 0.7367 - val_accuracy: 0.6806
Epoch 101/500
18/18 [==============================] - 0s 953us/step - loss: 0.3097 - accuracy: 0.8780 - val_loss: 0.7380 - val_accuracy: 0.6806
Epoch 102/500
18/18 [==============================] - 0s 964us/step - loss: 0.3092 - accuracy: 0.8711 - val_loss: 0.7376 - val_accuracy: 0.6806
Epoch 103/500
18/18 [==============================] - 0s 981us/step - loss: 0.3080 - accuracy: 0.8885 - val_loss: 0.7410 - val_accuracy: 0.6944
Epoch 104/500
18/18 [==============================] - 0s 964us/step - loss: 0.3052 - accuracy: 0.8746 - val_loss: 0.7451 - val_accuracy: 0.6944
Epoch 105/500
18/18 [==============================] - 0s 936us/step - loss: 0.3032 - accuracy: 0.8780 - val_loss: 0.7428 - val_accuracy: 0.6944
Epoch 106/500
18/18 [==============================] - 0s 953us/step - loss: 0.3022 - accuracy: 0.8920 - val_loss: 0.7489 - val_accuracy: 0.6806
Epoch 107/500
18/18 [==============================] - 0s 950us/step - loss: 0.3020 - accuracy: 0.8676 - val_loss: 0.7496 - val_accuracy: 0.6944
Epoch 108/500
18/18 [==============================] - 0s 945us/step - loss: 0.2984 - accuracy: 0.8850 - val_loss: 0.7510 - val_accuracy: 0.6944
Epoch 109/500
18/18 [==============================] - 0s 984us/step - loss: 0.2968 - accuracy: 0.8746 - val_loss: 0.7537 - val_accuracy: 0.6944
Epoch 110/500
18/18 [==============================] - 0s 974us/step - loss: 0.2958 - accuracy: 0.8711 - val_loss: 0.7546 - val_accuracy: 0.6944
Epoch 111/500
18/18 [==============================] - 0s 980us/step - loss: 0.2938 - accuracy: 0.8711 - val_loss: 0.7551 - val_accuracy: 0.6944
Epoch 112/500
18/18 [==============================] - 0s 992us/step - loss: 0.2918 - accuracy: 0.8746 - val_loss: 0.7579 - val_accuracy: 0.6944
Epoch 113/500
18/18 [==============================] - 0s 1ms/step - loss: 0.2906 - accuracy: 0.8746 - val_loss: 0.7609 - val_accuracy: 0.6944
Epoch 114/500
18/18 [==============================] - 0s 982us/step - loss: 0.2893 - accuracy: 0.8711 - val_loss: 0.7662 - val_accuracy: 0.6944

Epoch 115/500
18/18 [==============================] - 0s 969us/step - loss: 0.2882 - accuracy: 0.8676 - val_loss: 0.7655 - val_accuracy: 0.6944
Epoch 116/500
18/18 [==============================] - 0s 941us/step - loss: 0.2870 - accuracy: 0.9024 - val_loss: 0.7680 - val_accuracy: 0.6944
Epoch 117/500
18/18 [==============================] - 0s 933us/step - loss: 0.2851 - accuracy: 0.8850 - val_loss: 0.7720 - val_accuracy: 0.7083
Epoch 118/500
18/18 [==============================] - 0s 920us/step - loss: 0.2830 - accuracy: 0.8676 - val_loss: 0.7744 - val_accuracy: 0.6944
Epoch 119/500
18/18 [==============================] - 0s 933us/step - loss: 0.2822 - accuracy: 0.8780 - val_loss: 0.7712 - val_accuracy: 0.7083
Epoch 120/500
18/18 [==============================] - 0s 919us/step - loss: 0.2810 - accuracy: 0.8780 - val_loss: 0.7727 - val_accuracy: 0.7083
Epoch 121/500
18/18 [==============================] - 0s 933us/step - loss: 0.2790 - accuracy: 0.8815 - val_loss: 0.7735 - val_accuracy: 0.7083
Epoch 122/500
18/18 [==============================] - 0s 935us/step - loss: 0.2774 - accuracy: 0.8815 - val_loss: 0.7799 - val_accuracy: 0.7083
Epoch 123/500
18/18 [==============================] - 0s 943us/step - loss: 0.2763 - accuracy: 0.8920 - val_loss: 0.7823 - val_accuracy: 0.7083
Epoch 124/500
18/18 [==============================] - 0s 932us/step - loss: 0.2750 - accuracy: 0.8780 - val_loss: 0.7840 - val_accuracy: 0.7083
Epoch 125/500
18/18 [==============================] - 0s 1ms/step - loss: 0.2731 - accuracy: 0.8850 - val_loss: 0.7824 - val_accuracy: 0.7083

In [48]:
X_new = match_data_pre[370:371]

In [49]:
X_new = X_new.drop('home_win', axis = 1)
X_new = X_new.drop('away_win', axis = 1)
X_new = X_new.drop('gameweek', axis = 1)
X_new = X_new.drop('home_team_goal_count', axis = 1)
X_new = X_new.drop('away_team_goal_count', axis = 1)

In [50]:
model.predict(X_new)

1/1 [==============================] - 0s 33ms/step

array([[0.3225891, 0.6774109]], dtype=float32)

In [51]:
match_data_pre[370:371]

,home_team_goal_count,away_team_goal_count,away_team_away_percentage,home_team_home_percentage,home_team_name_AFC Bournemouth,home_team_name_Arsenal,home_team_name_Brighton & Hove Albion,home_team_name_Burnley,home_team_name_Cardiff City,home_team_name_Chelsea,...,away_team_name_Manchester United,away_team_name_Newcastle United,away_team_name_Southampton,away_team_name_Tottenham Hotspur,away_team_name_Watford,away_team_name_West Ham United,away_team_name_Wolverhampton Wanderers,home_win,away_win,gameweek
370,1,4,0.74,0.32,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,38

Model managed to find the correct answer, however the level of confidence is not high enough to be satisfied with the result of the model, therefore more fine tuning is necessary.

In [52]:
X_new_2 = match_data_pre[371:372]

In [53]:
X_new_2 = X_new_2.drop('home_win', axis = 1)
X_new_2 = X_new_2.drop('away_win', axis = 1)
X_new_2 = X_new_2.drop('gameweek', axis = 1)
X_new_2 = X_new_2.drop('home_team_goal_count', axis = 1)
X_new_2 = X_new_2.drop('away_team_goal_count', axis = 1)

In [54]:
X_new_2

,away_team_away_percentage,home_team_home_percentage,home_team_name_AFC Bournemouth,home_team_name_Arsenal,home_team_name_Brighton & Hove Albion,home_team_name_Burnley,home_team_name_Cardiff City,home_team_name_Chelsea,home_team_name_Crystal Palace,home_team_name_Everton,...,away_team_name_Leicester City,away_team_name_Liverpool,away_team_name_Manchester City,away_team_name_Manchester United,away_team_name_Newcastle United,away_team_name_Southampton,away_team_name_Tottenham Hotspur,away_team_name_Watford,away_team_name_West Ham United,away_team_name_Wolverhampton Wanderers
371,0.37,0.37,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [55]:
model.predict(X_new_2)

1/1 [==============================] - 0s 8ms/step

array([[0.45955536, 0.5404446 ]], dtype=float32)

Also correct on second test, however the confidence is still much too low.

## Improving the Data

In [56]:
match_data['Home Team Pre-Match xG'].tail(5)

375    1.96
376    1.67
377    1.46
378    1.71
379    1.30
Name: Home Team Pre-Match xG, dtype: float64

In [57]:
X_train['H_Pre_xG'] = match_data['Home Team Pre-Match xG']

In [58]:
X_train['A_Pre_xG'] = match_data['Away Team Pre-Match xG']

In [59]:
X_train

,away_team_away_percentage,home_team_home_percentage,home_team_name_AFC Bournemouth,home_team_name_Arsenal,home_team_name_Brighton & Hove Albion,home_team_name_Burnley,home_team_name_Cardiff City,home_team_name_Chelsea,home_team_name_Crystal Palace,home_team_name_Everton,...,away_team_name_Manchester City,away_team_name_Manchester United,away_team_name_Newcastle United,away_team_name_Southampton,away_team_name_Tottenham Hotspur,away_team_name_Watford,away_team_name_West Ham United,away_team_name_Wolverhampton Wanderers,H_Pre_xG,A_Pre_xG
0,0.37,0.53,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00
1,0.58,0.42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.00,0.00
2,0.21,0.42,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00
3,0.47,0.32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00
4,0.47,0.11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,0.26,0.26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.42,1.31
355,0.32,0.42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.32,1.27
356,0.21,0.32,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.25,1.02
357,0.37,0.42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.62,1.26
358,0.74,0.37,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.29,1.69

In [60]:
X_test['H_Pre_xG'] = match_data['Home Team Pre-Match xG'][360:370]
X_test['A_Pre_xG'] = match_data['Away Team Pre-Match xG'][360:370]

In [61]:
X_test

,away_team_away_percentage,home_team_home_percentage,home_team_name_AFC Bournemouth,home_team_name_Arsenal,home_team_name_Brighton & Hove Albion,home_team_name_Burnley,home_team_name_Cardiff City,home_team_name_Chelsea,home_team_name_Crystal Palace,home_team_name_Everton,...,away_team_name_Manchester City,away_team_name_Manchester United,away_team_name_Newcastle United,away_team_name_Southampton,away_team_name_Tottenham Hotspur,away_team_name_Watford,away_team_name_West Ham United,away_team_name_Wolverhampton Wanderers,H_Pre_xG,A_Pre_xG
360,0.21,0.53,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.52,0.99
361,0.58,0.42,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.31,1.38
362,0.21,0.47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.46,1.29
363,0.05,0.53,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.44,1.10
364,0.47,0.32,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.25,1.17
365,0.68,0.42,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.41,1.53
366,0.32,0.63,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.79,1.23
367,0.47,0.11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.25,1.40
368,0.16,0.74,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.57,1.00
369,0.37,0.95,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.24,1.39

In [90]:
def initialize_model_2():
    model = models.Sequential()
    
    model.add(layers.Dense(30, activation = 'relu', input_dim = X_train.shape[-1]))
    model.add(layers.Dense(20, activation = 'relu'))
    model.add(layers.Dense(10, activation = 'relu'))
    model.add(layers.Dense(7, activation = 'relu'))
    model.add(layers.Dense(2, activation = 'softmax'))
    
    return model

In [91]:
model = initialize_model_2()

In [92]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_13 (Dense)            (None, 30)                1350

 dense_14 (Dense)            (None, 20)                620

 dense_15 (Dense)            (None, 10)                210

 dense_16 (Dense)            (None, 7)                 77

 dense_17 (Dense)            (None, 2)                 16

=================================================================
Total params: 2,273
Trainable params: 2,273
Non-trainable params: 0
_________________________________________________________________

In [93]:
def compile_model_2(model, optimizer_name):
    model_compiled = model.compile(optimizer = optimizer_name,
                  loss = 'BinaryCrossentropy',
                  metrics='accuracy'
    )
    return model_compiled

In [94]:
opt = Adam(
    learning_rate=0.005, beta_1=0.9, beta_2=0.995
)

In [95]:
compile_model(model, 'Adam')

In [96]:
es = EarlyStopping(patience = 200, restore_best_weights=True)

history = model.fit(X_train, y_train, batch_size = 16, epochs = 500, validation_split = 0.2, callbacks = [es])

Epoch 1/500
18/18 [==============================] - 0s 5ms/step - loss: 0.6961 - accuracy: 0.3659 - val_loss: 0.6924 - val_accuracy: 0.4861
Epoch 2/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6909 - accuracy: 0.6063 - val_loss: 0.6899 - val_accuracy: 0.6806
Epoch 3/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6875 - accuracy: 0.7003 - val_loss: 0.6876 - val_accuracy: 0.6528
Epoch 4/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6838 - accuracy: 0.7003 - val_loss: 0.6846 - val_accuracy: 0.6389
Epoch 5/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6754 - accuracy: 0.6899 - val_loss: 0.6749 - val_accuracy: 0.6389
Epoch 6/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6609 - accuracy: 0.7003 - val_loss: 0.6617 - val_accuracy: 0.7222
Epoch 7/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6433 - accuracy: 0.7178 - val_loss: 0.6493 - val_accuracy: 0.7639
Epoch 8/500
18/18 [==============================] - 0s 1ms/step - loss: 0.6192 - accuracy: 0.7596 - val_loss: 0.6405 - val_accuracy: 0.6944
Epoch 9/500
18/18 [==============================] - 0s 1ms/step - loss: 0.5912 - accuracy: 0.7840 - val_loss: 0.6318 - val_accuracy: 0.6667
Epoch 10/500
18/18 [==============================] - 0s 1ms/step - loss: 0.5622 - accuracy: 0.7805 - val_loss: 0.6293 - val_accuracy: 0.6528
Epoch 11/500
18/18 [==============================] - 0s 1ms/step - loss: 0.5371 - accuracy: 0.7805 - val_loss: 0.6440 - val_accuracy: 0.6389
Epoch 12/500
18/18 [==============================] - 0s 1ms/step - loss: 0.5182 - accuracy: 0.7770 - val_loss: 0.6551 - val_accuracy: 0.6389
Epoch 13/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4954 - accuracy: 0.7909 - val_loss: 0.6783 - val_accuracy: 0.6528
Epoch 14/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4814 - accuracy: 0.8049 - val_loss: 0.6817 - val_accuracy: 0.6389
Epoch 15/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4832 - accuracy: 0.7979 - val_loss: 0.7035 - val_accuracy: 0.6389
Epoch 16/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4640 - accuracy: 0.8118 - val_loss: 0.7030 - val_accuracy: 0.6250
Epoch 17/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4537 - accuracy: 0.8153 - val_loss: 0.7187 - val_accuracy: 0.6667
Epoch 18/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4523 - accuracy: 0.8049 - val_loss: 0.7249 - val_accuracy: 0.6528
Epoch 19/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4488 - accuracy: 0.8014 - val_loss: 0.7412 - val_accuracy: 0.6389
Epoch 20/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4322 - accuracy: 0.8223 - val_loss: 0.7402 - val_accuracy: 0.6528
Epoch 21/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4182 - accuracy: 0.8362 - val_loss: 0.7523 - val_accuracy: 0.6528
Epoch 22/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4088 - accuracy: 0.8362 - val_loss: 0.7709 - val_accuracy: 0.6389
Epoch 23/500
18/18 [==============================] - 0s 1ms/step - loss: 0.4012 - accuracy: 0.8432 - val_loss: 0.7870 - val_accuracy: 0.6389
Epoch 24/500
18/18 [==============================] - 0s 1ms/step - loss: 0.3932 - accuracy: 0.8502 - val_loss: 0.7973 - val_accuracy: 0.6389
Epoch 25/500
18/18 [==============================] - 0s 1ms/step - loss: 0.3788 - accuracy: 0.8780 - val_loss: 0.8060 - val_accuracy: 0.6389
Epoch 26/500
18/18 [==============================] - 0s 1ms/step - loss: 0.3644 - accuracy: 0.8502 - val_loss: 0.8245 - val_accuracy: 0.6389
Epoch 27/500
18/18 [==============================] - 0s 1ms/step - loss: 0.3595 - accuracy: 0.8641 - val_loss: 0.8387 - val_accuracy: 0.6389
Epoch 28/500
18/18 [==============================] - 0s 1ms/step - loss: 0.3470 - accuracy: 0.8815 - val_loss: 0.8450 - val_accuracy: 0.6389
Epoch 29/500
18/18 [==============================] - 0s 1ms/step - loss: 0.3289 - accuracy: 0.9024 - val_loss: 0.8610 - val_accuracy: 0.6250
Epoch 30/500
18/18 [==============================] - 0s 1ms/step - loss: 0.3182 - accuracy: 0.8815 - val_loss: 0.8969 - val_accuracy: 0.6250
Epoch 31/500
18/18 [==============================] - 0s 1ms/step - loss: 0.3008 - accuracy: 0.8920 - val_loss: 0.9116 - val_accuracy: 0.6250
Epoch 32/500
18/18 [==============================] - 0s 1ms/step - loss: 0.2947 - accuracy: 0.8746 - val_loss: 0.9488 - val_accuracy: 0.6111
Epoch 33/500
18/18 [==============================] - 0s 2ms/step - loss: 0.2775 - accuracy: 0.8780 - val_loss: 0.9737 - val_accuracy: 0.6111
Epoch 34/500
18/18 [==============================] - 0s 2ms/step - loss: 0.2715 - accuracy: 0.8780 - val_loss: 1.0138 - val_accuracy: 0.6389
Epoch 35/500
18/18 [==============================] - 0s 1ms/step - loss: 0.2622 - accuracy: 0.8885 - val_loss: 1.0610 - val_accuracy: 0.6389
Epoch 36/500
18/18 [==============================] - 0s 1ms/step - loss: 0.2492 - accuracy: 0.8815 - val_loss: 1.0681 - val_accuracy: 0.6111
Epoch 37/500
18/18 [==============================] - 0s 1ms/step - loss: 0.2432 - accuracy: 0.9268 - val_loss: 1.0877 - val_accuracy: 0.6111
Epoch 38/500
18/18 [==============================] - 0s 1ms/step - loss: 0.2335 - accuracy: 0.8920 - val_loss: 1.1177 - val_accuracy: 0.6111
Epoch 39/500
18/18 [==============================] - 0s 1ms/step - loss: 0.2199 - accuracy: 0.9024 - val_loss: 1.1695 - val_accuracy: 0.5972
Epoch 40/500
18/18 [==============================] - 0s 1ms/step - loss: 0.2118 - accuracy: 0.9094 - val_loss: 1.2052 - val_accuracy: 0.6111
Epoch 41/500
18/18 [==============================] - 0s 1ms/step - loss: 0.2007 - accuracy: 0.9199 - val_loss: 1.2262 - val_accuracy: 0.6250
Epoch 42/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1937 - accuracy: 0.9094 - val_loss: 1.2989 - val_accuracy: 0.6111
Epoch 43/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1881 - accuracy: 0.9024 - val_loss: 1.3408 - val_accuracy: 0.6111
Epoch 44/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1807 - accuracy: 0.9094 - val_loss: 1.3540 - val_accuracy: 0.6111
Epoch 45/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1756 - accuracy: 0.8990 - val_loss: 1.4169 - val_accuracy: 0.6111
Epoch 46/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1706 - accuracy: 0.9199 - val_loss: 1.4349 - val_accuracy: 0.6111
Epoch 47/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1650 - accuracy: 0.9199 - val_loss: 1.4821 - val_accuracy: 0.6250
Epoch 48/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1609 - accuracy: 0.8990 - val_loss: 1.5185 - val_accuracy: 0.6250
Epoch 49/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1570 - accuracy: 0.9199 - val_loss: 1.5506 - val_accuracy: 0.6389
Epoch 50/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1549 - accuracy: 0.8990 - val_loss: 1.5882 - val_accuracy: 0.6111
Epoch 51/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1534 - accuracy: 0.9094 - val_loss: 1.6113 - val_accuracy: 0.6250
Epoch 52/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1518 - accuracy: 0.8850 - val_loss: 1.6569 - val_accuracy: 0.6250
Epoch 53/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1509 - accuracy: 0.8920 - val_loss: 1.6871 - val_accuracy: 0.6111
Epoch 54/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1499 - accuracy: 0.9303 - val_loss: 1.6930 - val_accuracy: 0.6389
Epoch 55/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1497 - accuracy: 0.8746 - val_loss: 1.7385 - val_accuracy: 0.6111
Epoch 56/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1488 - accuracy: 0.9094 - val_loss: 1.7469 - val_accuracy: 0.6111
Epoch 57/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1457 - accuracy: 0.9024 - val_loss: 1.7859 - val_accuracy: 0.5972
Epoch 58/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1519 - accuracy: 0.8885 - val_loss: 1.8267 - val_accuracy: 0.6111

Epoch 59/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1548 - accuracy: 0.9094 - val_loss: 1.7655 - val_accuracy: 0.5972
Epoch 60/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1492 - accuracy: 0.9024 - val_loss: 1.8172 - val_accuracy: 0.5972
Epoch 61/500
18/18 [==============================] - 0s 4ms/step - loss: 0.1439 - accuracy: 0.9094 - val_loss: 1.8281 - val_accuracy: 0.5972
Epoch 62/500
18/18 [==============================] - 0s 2ms/step - loss: 0.1450 - accuracy: 0.9094 - val_loss: 1.8588 - val_accuracy: 0.5972
Epoch 63/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1505 - accuracy: 0.8955 - val_loss: 1.8611 - val_accuracy: 0.6111
Epoch 64/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1522 - accuracy: 0.9129 - val_loss: 1.8536 - val_accuracy: 0.6111
Epoch 65/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1529 - accuracy: 0.9199 - val_loss: 1.8510 - val_accuracy: 0.5972
Epoch 66/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1492 - accuracy: 0.8815 - val_loss: 1.8697 - val_accuracy: 0.6250
Epoch 67/500
18/18 [==============================] - 0s 997us/step - loss: 0.1480 - accuracy: 0.9024 - val_loss: 1.8406 - val_accuracy: 0.6250
Epoch 68/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1427 - accuracy: 0.9059 - val_loss: 1.8845 - val_accuracy: 0.6111
Epoch 69/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1398 - accuracy: 0.9024 - val_loss: 1.9129 - val_accuracy: 0.5972
Epoch 70/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1398 - accuracy: 0.9164 - val_loss: 1.9377 - val_accuracy: 0.5972
Epoch 71/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1406 - accuracy: 0.9024 - val_loss: 1.9509 - val_accuracy: 0.6111
Epoch 72/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1418 - accuracy: 0.9094 - val_loss: 1.9901 - val_accuracy: 0.5972
Epoch 73/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1419 - accuracy: 0.8711 - val_loss: 1.9889 - val_accuracy: 0.5972
Epoch 74/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1473 - accuracy: 0.9338 - val_loss: 1.9942 - val_accuracy: 0.6111
Epoch 75/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1517 - accuracy: 0.8850 - val_loss: 1.9575 - val_accuracy: 0.6111
Epoch 76/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1476 - accuracy: 0.9129 - val_loss: 1.9560 - val_accuracy: 0.5972
Epoch 77/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1440 - accuracy: 0.8990 - val_loss: 1.9626 - val_accuracy: 0.6111
Epoch 78/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1452 - accuracy: 0.9059 - val_loss: 1.9976 - val_accuracy: 0.6111
Epoch 79/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1436 - accuracy: 0.8990 - val_loss: 2.0238 - val_accuracy: 0.5972
Epoch 80/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1424 - accuracy: 0.8885 - val_loss: 2.0255 - val_accuracy: 0.5972
Epoch 81/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1413 - accuracy: 0.9164 - val_loss: 2.0258 - val_accuracy: 0.5972
Epoch 82/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1430 - accuracy: 0.8920 - val_loss: 2.0245 - val_accuracy: 0.5972
Epoch 83/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1448 - accuracy: 0.9094 - val_loss: 2.0843 - val_accuracy: 0.6111
Epoch 84/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1468 - accuracy: 0.9199 - val_loss: 2.0460 - val_accuracy: 0.6111
Epoch 85/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1437 - accuracy: 0.9024 - val_loss: 2.0463 - val_accuracy: 0.5972
Epoch 86/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1427 - accuracy: 0.9094 - val_loss: 1.9968 - val_accuracy: 0.5972
Epoch 87/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1448 - accuracy: 0.8920 - val_loss: 2.0103 - val_accuracy: 0.5972
Epoch 88/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1394 - accuracy: 0.9129 - val_loss: 2.0443 - val_accuracy: 0.5972
Epoch 89/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1385 - accuracy: 0.9024 - val_loss: 2.0476 - val_accuracy: 0.6111
Epoch 90/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1378 - accuracy: 0.9129 - val_loss: 2.0668 - val_accuracy: 0.5972
Epoch 91/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1396 - accuracy: 0.8850 - val_loss: 2.0861 - val_accuracy: 0.5972
Epoch 92/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1406 - accuracy: 0.9164 - val_loss: 2.1001 - val_accuracy: 0.6111
Epoch 93/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1386 - accuracy: 0.9024 - val_loss: 2.1146 - val_accuracy: 0.6111
Epoch 94/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1378 - accuracy: 0.9094 - val_loss: 2.1067 - val_accuracy: 0.6111
Epoch 95/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1380 - accuracy: 0.8955 - val_loss: 2.1204 - val_accuracy: 0.6111
Epoch 96/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1381 - accuracy: 0.9338 - val_loss: 2.1499 - val_accuracy: 0.5972
Epoch 97/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1386 - accuracy: 0.9059 - val_loss: 2.1357 - val_accuracy: 0.5972
Epoch 98/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1412 - accuracy: 0.8990 - val_loss: 2.1665 - val_accuracy: 0.5972
Epoch 99/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1442 - accuracy: 0.8990 - val_loss: 2.1641 - val_accuracy: 0.6250
Epoch 100/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1517 - accuracy: 0.9164 - val_loss: 2.1263 - val_accuracy: 0.5972
Epoch 101/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1541 - accuracy: 0.8920 - val_loss: 2.1326 - val_accuracy: 0.6111
Epoch 102/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1482 - accuracy: 0.9059 - val_loss: 2.0551 - val_accuracy: 0.5972
Epoch 103/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1444 - accuracy: 0.9094 - val_loss: 2.0512 - val_accuracy: 0.6111
Epoch 104/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1402 - accuracy: 0.8955 - val_loss: 2.0869 - val_accuracy: 0.6111
Epoch 105/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1421 - accuracy: 0.9094 - val_loss: 2.0724 - val_accuracy: 0.5972
Epoch 106/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1503 - accuracy: 0.8955 - val_loss: 2.0684 - val_accuracy: 0.5972
Epoch 107/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1492 - accuracy: 0.9129 - val_loss: 2.0830 - val_accuracy: 0.5972
Epoch 108/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1439 - accuracy: 0.9059 - val_loss: 2.0820 - val_accuracy: 0.5972
Epoch 109/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1450 - accuracy: 0.9059 - val_loss: 2.0838 - val_accuracy: 0.6111
Epoch 110/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1444 - accuracy: 0.8850 - val_loss: 2.0931 - val_accuracy: 0.6250
Epoch 111/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1430 - accuracy: 0.9233 - val_loss: 2.0508 - val_accuracy: 0.5972
Epoch 112/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1429 - accuracy: 0.9233 - val_loss: 2.0722 - val_accuracy: 0.6111
Epoch 113/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1392 - accuracy: 0.8850 - val_loss: 2.0646 - val_accuracy: 0.6111
Epoch 114/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1389 - accuracy: 0.8955 - val_loss: 2.0955 - val_accuracy: 0.6111
Epoch 115/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1385 - accuracy: 0.8955 - val_loss: 2.0747 - val_accuracy: 0.6111
Epoch 116/500

18/18 [==============================] - 0s 1ms/step - loss: 0.1384 - accuracy: 0.9164 - val_loss: 2.1060 - val_accuracy: 0.6111
Epoch 117/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1393 - accuracy: 0.8990 - val_loss: 2.0923 - val_accuracy: 0.5972
Epoch 118/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1392 - accuracy: 0.9094 - val_loss: 2.1309 - val_accuracy: 0.5972
Epoch 119/500
18/18 [==============================] - 0s 991us/step - loss: 0.1400 - accuracy: 0.9024 - val_loss: 2.0943 - val_accuracy: 0.5972
Epoch 120/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1508 - accuracy: 0.8955 - val_loss: 2.1384 - val_accuracy: 0.5833
Epoch 121/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1536 - accuracy: 0.8815 - val_loss: 2.1179 - val_accuracy: 0.5972
Epoch 122/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1486 - accuracy: 0.9199 - val_loss: 2.0775 - val_accuracy: 0.6250
Epoch 123/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1448 - accuracy: 0.9233 - val_loss: 2.0666 - val_accuracy: 0.5972
Epoch 124/500
18/18 [==============================] - 0s 974us/step - loss: 0.1427 - accuracy: 0.8990 - val_loss: 2.0641 - val_accuracy: 0.5972
Epoch 125/500
18/18 [==============================] - 0s 1000us/step - loss: 0.1406 - accuracy: 0.8885 - val_loss: 2.0608 - val_accuracy: 0.6111
Epoch 126/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1386 - accuracy: 0.9059 - val_loss: 2.0537 - val_accuracy: 0.5972
Epoch 127/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1371 - accuracy: 0.9024 - val_loss: 2.0855 - val_accuracy: 0.5972
Epoch 128/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1362 - accuracy: 0.8955 - val_loss: 2.1005 - val_accuracy: 0.5972
Epoch 129/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1366 - accuracy: 0.9024 - val_loss: 2.1141 - val_accuracy: 0.5972
Epoch 130/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1355 - accuracy: 0.8885 - val_loss: 2.1256 - val_accuracy: 0.5972
Epoch 131/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1358 - accuracy: 0.9303 - val_loss: 2.1415 - val_accuracy: 0.5972
Epoch 132/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1355 - accuracy: 0.8746 - val_loss: 2.1578 - val_accuracy: 0.5972
Epoch 133/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1352 - accuracy: 0.9233 - val_loss: 2.1770 - val_accuracy: 0.5972
Epoch 134/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1350 - accuracy: 0.9129 - val_loss: 2.1891 - val_accuracy: 0.5972
Epoch 135/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1349 - accuracy: 0.8955 - val_loss: 2.2055 - val_accuracy: 0.5972
Epoch 136/500
18/18 [==============================] - 0s 999us/step - loss: 0.1348 - accuracy: 0.9094 - val_loss: 2.2153 - val_accuracy: 0.5972
Epoch 137/500
18/18 [==============================] - 0s 990us/step - loss: 0.1347 - accuracy: 0.8990 - val_loss: 2.2284 - val_accuracy: 0.5972
Epoch 138/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1346 - accuracy: 0.8920 - val_loss: 2.2401 - val_accuracy: 0.5972
Epoch 139/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1346 - accuracy: 0.8990 - val_loss: 2.2566 - val_accuracy: 0.5972
Epoch 140/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1344 - accuracy: 0.9303 - val_loss: 2.2656 - val_accuracy: 0.5972
Epoch 141/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1344 - accuracy: 0.9059 - val_loss: 2.2843 - val_accuracy: 0.5972
Epoch 142/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1345 - accuracy: 0.8920 - val_loss: 2.2850 - val_accuracy: 0.5972
Epoch 143/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1348 - accuracy: 0.9164 - val_loss: 2.3016 - val_accuracy: 0.5833
Epoch 144/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1354 - accuracy: 0.8920 - val_loss: 2.3168 - val_accuracy: 0.5972
Epoch 145/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1356 - accuracy: 0.9059 - val_loss: 2.3117 - val_accuracy: 0.5833
Epoch 146/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1357 - accuracy: 0.9024 - val_loss: 2.3299 - val_accuracy: 0.5972
Epoch 147/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1364 - accuracy: 0.8920 - val_loss: 2.3386 - val_accuracy: 0.5833
Epoch 148/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1375 - accuracy: 0.8990 - val_loss: 2.2891 - val_accuracy: 0.5972
Epoch 149/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1404 - accuracy: 0.9059 - val_loss: 2.3051 - val_accuracy: 0.5833
Epoch 150/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1450 - accuracy: 0.9129 - val_loss: 2.3324 - val_accuracy: 0.5972
Epoch 151/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1446 - accuracy: 0.8990 - val_loss: 2.2780 - val_accuracy: 0.5833
Epoch 152/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1389 - accuracy: 0.8920 - val_loss: 2.2956 - val_accuracy: 0.5972
Epoch 153/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1513 - accuracy: 0.9303 - val_loss: 2.2420 - val_accuracy: 0.5972
Epoch 154/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1462 - accuracy: 0.8885 - val_loss: 2.1878 - val_accuracy: 0.5972
Epoch 155/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1457 - accuracy: 0.8955 - val_loss: 2.1902 - val_accuracy: 0.5972
Epoch 156/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1540 - accuracy: 0.9059 - val_loss: 2.1397 - val_accuracy: 0.5833
Epoch 157/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1630 - accuracy: 0.9024 - val_loss: 2.1507 - val_accuracy: 0.6111
Epoch 158/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1441 - accuracy: 0.9199 - val_loss: 2.1245 - val_accuracy: 0.6111
Epoch 159/500
18/18 [==============================] - 0s 983us/step - loss: 0.1464 - accuracy: 0.8955 - val_loss: 2.1329 - val_accuracy: 0.6111
Epoch 160/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1421 - accuracy: 0.9233 - val_loss: 2.1310 - val_accuracy: 0.5833
Epoch 161/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1439 - accuracy: 0.8746 - val_loss: 2.1511 - val_accuracy: 0.5972
Epoch 162/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1411 - accuracy: 0.9024 - val_loss: 2.1114 - val_accuracy: 0.5833
Epoch 163/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1379 - accuracy: 0.9024 - val_loss: 2.1648 - val_accuracy: 0.5833
Epoch 164/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1386 - accuracy: 0.8990 - val_loss: 2.1373 - val_accuracy: 0.6111
Epoch 165/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1384 - accuracy: 0.9199 - val_loss: 2.1673 - val_accuracy: 0.5972
Epoch 166/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1368 - accuracy: 0.8850 - val_loss: 2.1877 - val_accuracy: 0.5972
Epoch 167/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1366 - accuracy: 0.9338 - val_loss: 2.1924 - val_accuracy: 0.5833
Epoch 168/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1359 - accuracy: 0.8920 - val_loss: 2.1924 - val_accuracy: 0.5833
Epoch 169/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1356 - accuracy: 0.8885 - val_loss: 2.2143 - val_accuracy: 0.5972
Epoch 170/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1352 - accuracy: 0.9129 - val_loss: 2.2072 - val_accuracy: 0.5833
Epoch 171/500
18/18 [==============================] - 0s 999us/step - loss: 0.1351 - accuracy: 0.9059 - val_loss: 2.2402 - val_accuracy: 0.5833
Epoch 172/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1350 - accuracy: 0.9129 - val_loss: 2.2411 - val_accuracy: 0.5972
Epoch 173/500

18/18 [==============================] - 0s 1ms/step - loss: 0.1350 - accuracy: 0.9024 - val_loss: 2.2648 - val_accuracy: 0.5833
Epoch 174/500
18/18 [==============================] - 0s 968us/step - loss: 0.1349 - accuracy: 0.8920 - val_loss: 2.2712 - val_accuracy: 0.5833
Epoch 175/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1349 - accuracy: 0.8815 - val_loss: 2.2845 - val_accuracy: 0.5833
Epoch 176/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1349 - accuracy: 0.9233 - val_loss: 2.2887 - val_accuracy: 0.5833
Epoch 177/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1351 - accuracy: 0.8990 - val_loss: 2.2928 - val_accuracy: 0.5833
Epoch 178/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1363 - accuracy: 0.8955 - val_loss: 2.2994 - val_accuracy: 0.5833
Epoch 179/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1364 - accuracy: 0.8850 - val_loss: 2.3173 - val_accuracy: 0.5833
Epoch 180/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1394 - accuracy: 0.9164 - val_loss: 2.2786 - val_accuracy: 0.5972
Epoch 181/500
18/18 [==============================] - 0s 998us/step - loss: 0.1400 - accuracy: 0.8990 - val_loss: 2.2581 - val_accuracy: 0.5833
Epoch 182/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1382 - accuracy: 0.8990 - val_loss: 2.3025 - val_accuracy: 0.5833
Epoch 183/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1387 - accuracy: 0.8815 - val_loss: 2.2828 - val_accuracy: 0.5833
Epoch 184/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1406 - accuracy: 0.9199 - val_loss: 2.2834 - val_accuracy: 0.6111
Epoch 185/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1441 - accuracy: 0.9129 - val_loss: 2.2451 - val_accuracy: 0.5833
Epoch 186/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1460 - accuracy: 0.8885 - val_loss: 2.2648 - val_accuracy: 0.6111
Epoch 187/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1499 - accuracy: 0.9233 - val_loss: 2.2532 - val_accuracy: 0.6111
Epoch 188/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1441 - accuracy: 0.9024 - val_loss: 2.1877 - val_accuracy: 0.6111
Epoch 189/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1416 - accuracy: 0.8955 - val_loss: 2.2119 - val_accuracy: 0.5972
Epoch 190/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1410 - accuracy: 0.9129 - val_loss: 2.1824 - val_accuracy: 0.5833
Epoch 191/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1433 - accuracy: 0.8885 - val_loss: 2.1948 - val_accuracy: 0.6111
Epoch 192/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1463 - accuracy: 0.9233 - val_loss: 2.2024 - val_accuracy: 0.6111
Epoch 193/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1432 - accuracy: 0.9024 - val_loss: 2.1940 - val_accuracy: 0.5972
Epoch 194/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1380 - accuracy: 0.9024 - val_loss: 2.1943 - val_accuracy: 0.5833
Epoch 195/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1387 - accuracy: 0.8850 - val_loss: 2.1870 - val_accuracy: 0.6111
Epoch 196/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1372 - accuracy: 0.9129 - val_loss: 2.2170 - val_accuracy: 0.5833
Epoch 197/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1376 - accuracy: 0.9059 - val_loss: 2.1962 - val_accuracy: 0.5833
Epoch 198/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1365 - accuracy: 0.8990 - val_loss: 2.2344 - val_accuracy: 0.5833
Epoch 199/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1358 - accuracy: 0.8990 - val_loss: 2.2214 - val_accuracy: 0.5833
Epoch 200/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1356 - accuracy: 0.8885 - val_loss: 2.2605 - val_accuracy: 0.6111
Epoch 201/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1354 - accuracy: 0.9199 - val_loss: 2.2701 - val_accuracy: 0.5833
Epoch 202/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1353 - accuracy: 0.8850 - val_loss: 2.2724 - val_accuracy: 0.5833
Epoch 203/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1352 - accuracy: 0.9059 - val_loss: 2.2837 - val_accuracy: 0.6111
Epoch 204/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1363 - accuracy: 0.9164 - val_loss: 2.2773 - val_accuracy: 0.5833
Epoch 205/500
18/18 [==============================] - 0s 1000us/step - loss: 0.1370 - accuracy: 0.8920 - val_loss: 2.3055 - val_accuracy: 0.5833
Epoch 206/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1360 - accuracy: 0.8955 - val_loss: 2.3267 - val_accuracy: 0.5972
Epoch 207/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1358 - accuracy: 0.9268 - val_loss: 2.3178 - val_accuracy: 0.5833
Epoch 208/500
18/18 [==============================] - 0s 992us/step - loss: 0.1364 - accuracy: 0.8780 - val_loss: 2.3158 - val_accuracy: 0.5833
Epoch 209/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1379 - accuracy: 0.8955 - val_loss: 2.3157 - val_accuracy: 0.5833
Epoch 210/500
18/18 [==============================] - 0s 1ms/step - loss: 0.1375 - accuracy: 0.9268 - val_loss: 2.3282 - val_accuracy: 0.5833

In [97]:
X_new = match_data_pre[370:371]

In [98]:
X_new = X_new.drop('home_win', axis = 1)
X_new = X_new.drop('away_win', axis = 1)
X_new = X_new.drop('gameweek', axis = 1)
X_new = X_new.drop('home_team_goal_count', axis = 1)
X_new = X_new.drop('away_team_goal_count', axis = 1)

In [99]:
X_new['H_Pre_xG'] = match_data['Home Team Pre-Match xG'][370:371]
X_new['A_Pre_xG'] = match_data['Away Team Pre-Match xG'][370:371]

In [100]:
model.predict(X_new)

1/1 [==============================] - 0s 27ms/step

array([[0.23694919, 0.7630508 ]], dtype=float32)

In [101]:
X_new_2 = match_data_pre[371:372]
X_new_2 = X_new_2.drop('home_win', axis = 1)
X_new_2 = X_new_2.drop('away_win', axis = 1)
X_new_2 = X_new_2.drop('gameweek', axis = 1)
X_new_2 = X_new_2.drop('home_team_goal_count', axis = 1)
X_new_2 = X_new_2.drop('away_team_goal_count', axis = 1)

In [102]:
X_new_2['H_Pre_xG'] = match_data['Home Team Pre-Match xG'][371:372]
X_new_2['A_Pre_xG'] = match_data['Away Team Pre-Match xG'][371:372]

In [103]:
model.predict(X_new_2)

1/1 [==============================] - 0s 7ms/step

array([[0.2524754 , 0.74752456]], dtype=float32)

In [106]:
X_new_3 = match_data_pre[375:376]

In [108]:
X_new_3 = X_new_3.drop('home_win', axis = 1)
X_new_3 = X_new_3.drop('away_win', axis = 1)
X_new_3 = X_new_3.drop('gameweek', axis = 1)
X_new_3 = X_new_3.drop('home_team_goal_count', axis = 1)
X_new_3 = X_new_3.drop('away_team_goal_count', axis = 1)

In [109]:
X_new_3['H_Pre_xG'] = match_data['Home Team Pre-Match xG'][375:376]
X_new_3['A_Pre_xG'] = match_data['Away Team Pre-Match xG'][375:376]

In [110]:
model.predict(X_new_3)

1/1 [==============================] - 0s 10ms/step

array([[0.92046255, 0.07953748]], dtype=float32)

# Going for Player stats

## Removing Unnecessary Data

In [111]:
player_data = pd.read_csv('data/england-premier-league-players-2018-to-2019-stats.csv')

In [122]:
player_data.head(5)

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,annual_salary_eur_percentile,clean_sheets_percentage_percentile_overall,min_per_card_percentile_overall,cards_per90_percentile_overall,booked_over05_overall,booked_over05_percentage_overall,booked_over05_percentage_percentile_overall,shirt_number,annual_salary_gbp,annual_salary_usd
0,Aaron Cresswell,32,629712000,1989/12/15,Premier League,2018/2019,Defender,West Ham United,1589,888,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aaron Lennon,35,545554800,1987/04/16,Premier League,2018/2019,Midfielder,Burnley,1217,487,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aaron Mooy,32,653382000,1990/09/15,Premier League,2018/2019,Midfielder,Huddersfield Town,2327,1190,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aaron Ramsey,31,662198400,1990/12/26,Premier League,2018/2019,Midfielder,Arsenal,1327,689,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aaron Rowe,22,968310000,2000/09/07,Premier League,2018/2019,Forward,Huddersfield Town,69,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
player_data.isna()

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,annual_salary_eur_percentile,clean_sheets_percentage_percentile_overall,min_per_card_percentile_overall,cards_per90_percentile_overall,booked_over05_overall,booked_over05_percentage_overall,booked_over05_percentage_percentile_overall,shirt_number,annual_salary_gbp,annual_salary_usd
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
566,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
567,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
568,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
569,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True

In [125]:
player_data.dropna(axis = 1, inplace=True)

In [126]:
player_data

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
0,Aaron Cresswell,32,629712000,1989/12/15,Premier League,2018/2019,Defender,West Ham United,1589,888,...,1.25,72,79,1589,1589,0.06,290,191,80,20
1,Aaron Lennon,35,545554800,1987/04/16,Premier League,2018/2019,Midfielder,Burnley,1217,487,...,1.48,61,76,1217,1217,0.07,196,187,-1,10
2,Aaron Mooy,32,653382000,1990/09/15,Premier League,2018/2019,Midfielder,Huddersfield Town,2327,1190,...,1.78,51,80,582,2327,0.15,144,233,-1,3
3,Aaron Ramsey,31,662198400,1990/12/26,Premier League,2018/2019,Midfielder,Arsenal,1327,689,...,0.81,111,47,0,221,0.00,69,8,-1,5
4,Aaron Rowe,22,968310000,2000/09/07,Premier League,2018/2019,Forward,Huddersfield Town,69,14,...,1.30,69,35,0,0,0.00,-1,-1,-1,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,Youri Tielemans,25,862988400,1997/05/07,Premier League,2018/2019,Midfielder,Leicester City,1092,575,...,1.07,84,84,546,273,0.16,80,13,-1,4
566,Yves Bissouma,26,841388400,1996/08/30,Premier League,2018/2019,Midfielder,Brighton & Hove Albion,1769,747,...,1.53,59,63,354,0,0.25,402,293,-1,17
567,Zechariah Medley,22,962953200,2000/07/07,Premier League,2018/2019,Defender,Arsenal,0,0,...,0.00,0,0,0,0,0.00,-1,-1,-1,-1
568,Zeze Steven Sessegnon,22,958633200,2000/05/18,Premier League,2018/2019,Defender,Fulham,0,0,...,0.00,0,0,0,0,0.00,-1,-1,-1,-1
569,Łukasz Fabiański,37,482659200,1985/04/18,Premier League,2018/2019,Goalkeeper,West Ham United,3420,1710,...,1.26,71,90,0,0,0.00,391,343,81,19

In [128]:
player_data.drop('birthday', axis = 1, inplace = True)
player_data.drop('birthday_GMT', axis = 1, inplace = True)
player_data.drop('age', axis = 1, inplace = True)

In [129]:
player_data.drop('league', axis = 1, inplace = True)

In [130]:
player_data

,full_name,season,position,Current Club,minutes_played_overall,minutes_played_home,minutes_played_away,nationality,appearances_overall,appearances_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
0,Aaron Cresswell,2018/2019,Defender,West Ham United,1589,888,701,England,20,11,...,1.25,72,79,1589,1589,0.06,290,191,80,20
1,Aaron Lennon,2018/2019,Midfielder,Burnley,1217,487,730,England,16,7,...,1.48,61,76,1217,1217,0.07,196,187,-1,10
2,Aaron Mooy,2018/2019,Midfielder,Huddersfield Town,2327,1190,1137,Australia,29,15,...,1.78,51,80,582,2327,0.15,144,233,-1,3
3,Aaron Ramsey,2018/2019,Midfielder,Arsenal,1327,689,638,Wales,28,14,...,0.81,111,47,0,221,0.00,69,8,-1,5
4,Aaron Rowe,2018/2019,Forward,Huddersfield Town,69,14,55,England,2,1,...,1.30,69,35,0,0,0.00,-1,-1,-1,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,Youri Tielemans,2018/2019,Midfielder,Leicester City,1092,575,517,Belgium,13,7,...,1.07,84,84,546,273,0.16,80,13,-1,4
566,Yves Bissouma,2018/2019,Midfielder,Brighton & Hove Albion,1769,747,1022,Mali,28,13,...,1.53,59,63,354,0,0.25,402,293,-1,17
567,Zechariah Medley,2018/2019,Defender,Arsenal,0,0,0,England,0,0,...,0.00,0,0,0,0,0.00,-1,-1,-1,-1
568,Zeze Steven Sessegnon,2018/2019,Defender,Fulham,0,0,0,England,0,0,...,0.00,0,0,0,0,0.00,-1,-1,-1,-1
569,Łukasz Fabiański,2018/2019,Goalkeeper,West Ham United,3420,1710,1710,Poland,38,19,...,1.26,71,90,0,0,0.00,391,343,81,19

In [131]:
player_data.drop('nationality', axis = 1, inplace = True)

In [132]:
player_data

,full_name,season,position,Current Club,minutes_played_overall,minutes_played_home,minutes_played_away,appearances_overall,appearances_home,appearances_away,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
0,Aaron Cresswell,2018/2019,Defender,West Ham United,1589,888,701,20,11,9,...,1.25,72,79,1589,1589,0.06,290,191,80,20
1,Aaron Lennon,2018/2019,Midfielder,Burnley,1217,487,730,16,7,9,...,1.48,61,76,1217,1217,0.07,196,187,-1,10
2,Aaron Mooy,2018/2019,Midfielder,Huddersfield Town,2327,1190,1137,29,15,14,...,1.78,51,80,582,2327,0.15,144,233,-1,3
3,Aaron Ramsey,2018/2019,Midfielder,Arsenal,1327,689,638,28,14,14,...,0.81,111,47,0,221,0.00,69,8,-1,5
4,Aaron Rowe,2018/2019,Forward,Huddersfield Town,69,14,55,2,1,1,...,1.30,69,35,0,0,0.00,-1,-1,-1,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,Youri Tielemans,2018/2019,Midfielder,Leicester City,1092,575,517,13,7,6,...,1.07,84,84,546,273,0.16,80,13,-1,4
566,Yves Bissouma,2018/2019,Midfielder,Brighton & Hove Albion,1769,747,1022,28,13,15,...,1.53,59,63,354,0,0.25,402,293,-1,17
567,Zechariah Medley,2018/2019,Defender,Arsenal,0,0,0,0,0,0,...,0.00,0,0,0,0,0.00,-1,-1,-1,-1
568,Zeze Steven Sessegnon,2018/2019,Defender,Fulham,0,0,0,0,0,0,...,0.00,0,0,0,0,0.00,-1,-1,-1,-1
569,Łukasz Fabiański,2018/2019,Goalkeeper,West Ham United,3420,1710,1710,38,19,19,...,1.26,71,90,0,0,0.00,391,343,81,19

In [133]:
player_data.shape

(570, 42)

## Preprocessing the Data

In [136]:
player_data.isna().count()

full_name                         570
season                            570
position                          570
Current Club                      570
minutes_played_overall            570
minutes_played_home               570
minutes_played_away               570
appearances_overall               570
appearances_home                  570
appearances_away                  570
goals_overall                     570
goals_home                        570
goals_away                        570
assists_overall                   570
assists_home                      570
assists_away                      570
penalty_goals                     570
penalty_misses                    570
clean_sheets_overall              570
clean_sheets_home                 570
clean_sheets_away                 570
conceded_overall                  570
conceded_home                     570
conceded_away                     570
yellow_cards_overall              570
red_cards_overall                 570
goals_involved_per_90_overall     570
assists_per_90_overall            570
goals_per_90_overall              570
goals_per_90_home                 570
goals_per_90_away                 570
min_per_goal_overall              570
conceded_per_90_overall           570
min_per_conceded_overall          570
min_per_match                     570
min_per_card_overall              570
min_per_assist_overall            570
cards_per_90_overall              570
rank_in_league_top_attackers      570
rank_in_league_top_midfielders    570
rank_in_league_top_defenders      570
rank_in_club_top_scorer           570
dtype: int64